### PR TITLE
Add Json validator workflow, fix prettier not submitting changes on push

### PR DESCRIPTION
**Pull request by Mr-Auto**

### CODE REVIEW

**Comment by Mr-Auto** [comment]
example of an error 
image

**Comment by zappatic** [comment]
Is this completed?

**Comment by Mr-Auto** [comment]
> Is this completed?

I guess, unless you have some objections 
I think wanted to test something more, but honestly i forgot what xd

**Comment by zappatic** [comment]
No, go ahead if you want to test more, it's fine, I was just wondering whether I had forgotten to merge this.

**Comment by Mr-Auto** [comment]
> No, go ahead if you want to test more, it's fine, I was just wondering whether I had forgotten to merge this.

The thing is, i don't remember what i wanted to test. And anyway, if i wouldn't want this to be merged i would make it into draft

**Pull request merged**
