### PR TITLE
Monsters update

### PR DESCRIPTION
**Pull request by Mr-Auto**

### CODE REVIEW

**Comment by Mr-Auto** [comment]
i just post it here: Anubis and AnubisTwo marge Yes/No

**Comment by zappatic** [comment]
No need for the anubis change, I have done it in my local copy already

**Comment by Mr-Auto** [comment]
HornedLizard and Frog could potentially by one type? not worth merging tho, i think

**Comment by Mr-Auto** [comment]
ok, that's all, can i ask you to take a look at:
GHIST, STORAGEGUY, HUNDUNS_SERVANT, BODYGUARD, THIEF, OLD_HUNTER, SISTER', YANG, MERCHANT, SHOPKEEPER

those got the most changes, i want to make sure those are now correct before we change those in ovelunky, maybe you will resolve some of the unknowns or give some naming suggestions.

in the mean time i will start working on my PR to implement/change stuff

**Pull request merged**
