### PR TITLE
Github Workflows Cache and Checks

### PR DESCRIPTION
**Pull request by Mr-Auto**
Clang format does not do any changes automatically, just check, can be run manually from Actions with push automatic changes if needed. Prettier can also be run manually but that should not be necessary

I was lazy so i just made `autobuild.yml` do everything about Building and Pull Requests:

- It will call Prettier to format the Spelunky2.json file (skipped for PR's)
- Get QT from cache if exists and build
- And as normal create release (skipped for PR's)

### CODE REVIEW

**Comment by Mr-Auto** [comment]
When merged to main and made a cache on main, that cache should be available for all pull requests, builds etc.

**Comment by Mr-Auto** [comment]
I will not fix the clang format errors in this PR as it would just cause conflicts with the other branch
@zappatic After you merge, you can also setup the checks as required for merge. The autobuild makes the most sense

**Comment by zappatic** [comment]
> After you merge, you can also setup the checks as required for merge. 

Can you elaborate on this?

**Comment by Mr-Auto** [comment]
> > After you merge, you can also setup the checks as required for merge.
> 
> Can you elaborate on this?

Just a suggestion. Probably doesn't matter for such small project

**Comment by zappatic** [comment]
> > > After you merge, you can also setup the checks as required for merge.
> > 
> > 
> > Can you elaborate on this?
> 
> Just a suggestion. Probably doesn't matter for such small project

No, I mean that I don't understand what your suggestion means. What checks would need to be setup where?

**Comment by Mr-Auto** [comment]
> > > > After you merge, you can also setup the checks as required for merge.
> > > 
> > > 
> > > Can you elaborate on this?
> > 
> > 
> > Just a suggestion. Probably doesn't matter for such small project
> 
> No, I mean that I don't understand what your suggestion means. What checks would need to be setup where?

`Settings->Branches->Add branch protection rule`, among the rules there is "Require status checks to pass before merging" where you can choose an action that has to pass, if PR fails this action/check it will not be possible to merge it

**Pull request merged**
